/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visão;

import modeloDAO.DAOPaciente;
import modeloBeans.BeansPaciente;

/**
 *
 * @author lenovo
 */
public class TelaPacientes extends javax.swing.JFrame {

    BeansPaciente paciente = new BeansPaciente();
    DAOPaciente control = new DAOPaciente();
    /**
     * Creates new form Pacientes
     */
    public TelaPacientes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitulo = new javax.swing.JLabel();
        jLabelNome = new javax.swing.JLabel();
        jTextFieldNomePaciente = new javax.swing.JTextField();
        jLabelCpf = new javax.swing.JLabel();
        jTextFieldCpf = new javax.swing.JTextField();
        jLabelIdade = new javax.swing.JLabel();
        jTextFieldIdade = new javax.swing.JTextField();
        jButtonSalvar = new javax.swing.JButton();
        jButtonSair = new javax.swing.JButton();
        jButtonConfiguraçao = new javax.swing.JButton();
        jButtonVoltar = new javax.swing.JButton();
        jLabelBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabelTitulo.setBackground(new java.awt.Color(255, 255, 255));
        jLabelTitulo.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitulo.setText("Cadastrar Pacientes");
        jLabelTitulo.setToolTipText("");
        getContentPane().add(jLabelTitulo);
        jLabelTitulo.setBounds(240, 30, 340, 42);

        jLabelNome.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelNome.setForeground(new java.awt.Color(102, 255, 255));
        jLabelNome.setText("Digite o nome do Paciente:");
        getContentPane().add(jLabelNome);
        jLabelNome.setBounds(30, 220, 260, 22);
        getContentPane().add(jTextFieldNomePaciente);
        jTextFieldNomePaciente.setBounds(280, 220, 430, 20);

        jLabelCpf.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelCpf.setForeground(new java.awt.Color(102, 255, 255));
        jLabelCpf.setText("Digite seu cpf:");
        getContentPane().add(jLabelCpf);
        jLabelCpf.setBounds(140, 290, 150, 20);

        jTextFieldCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCpfActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldCpf);
        jTextFieldCpf.setBounds(280, 290, 290, 20);

        jLabelIdade.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelIdade.setForeground(new java.awt.Color(153, 255, 255));
        jLabelIdade.setText("Digite a idade:");
        getContentPane().add(jLabelIdade);
        jLabelIdade.setBounds(140, 350, 140, 22);

        jTextFieldIdade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIdadeActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldIdade);
        jTextFieldIdade.setBounds(280, 350, 100, 20);

        jButtonSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-adicionar-15.png"))); // NOI18N
        jButtonSalvar.setText("salvar");
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSalvar);
        jButtonSalvar.setBounds(410, 350, 80, 23);

        jButtonSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-sair-17.png"))); // NOI18N
        jButtonSair.setToolTipText("Sair");
        jButtonSair.setContentAreaFilled(false);
        getContentPane().add(jButtonSair);
        jButtonSair.setBounds(60, 0, 60, 20);

        jButtonConfiguraçao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-configuração-de-segurança-17.png"))); // NOI18N
        jButtonConfiguraçao.setToolTipText("Configuração");
        jButtonConfiguraçao.setContentAreaFilled(false);
        jButtonConfiguraçao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfiguraçaoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonConfiguraçao);
        jButtonConfiguraçao.setBounds(120, 0, 60, 20);

        jButtonVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-voltar-16.png"))); // NOI18N
        jButtonVoltar.setToolTipText("Voltar para tela anterior");
        jButtonVoltar.setContentAreaFilled(false);
        jButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonVoltar);
        jButtonVoltar.setBounds(0, 0, 60, 20);

        jLabelBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/teladeFundo.jpg"))); // NOI18N
        getContentPane().add(jLabelBackground);
        jLabelBackground.setBounds(0, 0, 801, 521);

        setBounds(0, 0, 815, 602);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCpfActionPerformed

    private void jTextFieldIdadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIdadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIdadeActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        paciente.setNomePaciente(jTextFieldNomePaciente.getText());
        paciente.setCpf(jTextFieldCpf.getText());
        paciente.setIdade(jTextFieldIdade.getText());
        control.Salvar(paciente);
        TelaPrincipal tela= new TelaPrincipal();
       tela.setVisible(true);
       dispose();
        
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jButtonConfiguraçaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfiguraçaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonConfiguraçaoActionPerformed

    private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarActionPerformed
        // TODO add your handling code here:
       TelaPrincipal tela= new TelaPrincipal();
       tela.setVisible(true);
       dispose();
    }//GEN-LAST:event_jButtonVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPacientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPacientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPacientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPacientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPacientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonConfiguraçao;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JLabel jLabelBackground;
    private javax.swing.JLabel jLabelCpf;
    private javax.swing.JLabel jLabelIdade;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JTextField jTextFieldCpf;
    private javax.swing.JTextField jTextFieldIdade;
    private javax.swing.JTextField jTextFieldNomePaciente;
    // End of variables declaration//GEN-END:variables
}
